/*
Portions Copyright (c) Microsoft Corporation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// AgentPoolSecurityProfile agent pool security profile
//
// swagger:model AgentPoolSecurityProfile
type AgentPoolSecurityProfile struct {

	// enable secure boot
	EnableSecureBoot *bool `json:"enableSecureBoot,omitempty"`

	// enable v t p m
	EnableVTPM *bool `json:"enableVTPM,omitempty"`

	// ssh access
	SSHAccess *int32 `json:"sshAccess,omitempty"`
}

// Validate validates this agent pool security profile
func (m *AgentPoolSecurityProfile) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// ContextValidate validates this agent pool security profile based on context it is used
	return nil
}

func (m *AgentPoolSecurityProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *AgentPoolSecurityProfile) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *AgentPoolSecurityProfile) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
