/*
Portions Copyright (c) Microsoft Corporation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CustomLinuxOSConfig custom linux o s config
//
// swagger:model CustomLinuxOSConfig
type CustomLinuxOSConfig struct {

	// swap file size m b
	SwapFileSizeMB *int32 `json:"swapFileSizeMB,omitempty"`

	// sysctls
	Sysctls *SysctlConfig `json:"sysctls,omitempty"`

	// transparent huge page defrag
	TransparentHugePageDefrag *string `json:"transparentHugePageDefrag,omitempty"`

	// transparent huge page enabled
	TransparentHugePageEnabled *string `json:"transparentHugePageEnabled,omitempty"`

	// ulimits
	Ulimits *UlimitConfig `json:"ulimits,omitempty"`
}

// Validate validates this custom linux o s config
func (m *CustomLinuxOSConfig) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CustomLinuxOSConfig) validateSysctls(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

func (m *CustomLinuxOSConfig) validateUlimits(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

// ContextValidate validate this custom linux o s config based on the context it is used
func (m *CustomLinuxOSConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CustomLinuxOSConfig) contextValidateSysctls(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *CustomLinuxOSConfig) contextValidateUlimits(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

// MarshalBinary interface implementation
func (m *CustomLinuxOSConfig) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *CustomLinuxOSConfig) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
