/*
Portions Copyright (c) Microsoft Corporation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ProvisionProfile provision profile
//
// swagger:model ProvisionProfile
type ProvisionProfile struct {

	// agent pool windows profile
	AgentPoolWindowsProfile *AgentPoolWindowsProfile `json:"agentPoolWindowsProfile,omitempty"`

	// architecture
	// Required: true
	Architecture *string `json:"architecture"`

	// artifact streaming profile
	ArtifactStreamingProfile *ArtifactStreamingProfile `json:"artifactStreamingProfile,omitempty"`

	// custom kubelet config
	CustomKubeletConfig *CustomKubeletConfig `json:"customKubeletConfig,omitempty"`

	// custom linux o s config
	CustomLinuxOSConfig *CustomLinuxOSConfig `json:"customLinuxOSConfig,omitempty"`

	// custom node labels
	CustomNodeLabels map[string]string `json:"customNodeLabels,omitempty"`

	// distro
	// Required: true
	Distro *string `json:"distro"`

	// enable f IP s
	EnableFIPS *bool `json:"enableFIPS,omitempty"`

	// gpu instance profile
	GpuInstanceProfile *int32 `json:"gpuInstanceProfile,omitempty"`

	// gpu profile
	GpuProfile *GPUProfile `json:"gpuProfile,omitempty"`

	// kubelet disk type
	KubeletDiskType *int32 `json:"kubeletDiskType,omitempty"`

	// local DNS profile
	LocalDNSProfile *LocalDNSProfile `json:"localDNSProfile,omitempty"`

	// max pods
	// Required: true
	MaxPods *int32 `json:"maxPods"`

	// message of the day
	MessageOfTheDay *string `json:"messageOfTheDay,omitempty"`

	// mode
	// Required: true
	Mode *int32 `json:"mode"`

	// name
	// Required: true
	Name *string `json:"name"`

	// node initialization taints
	NodeInitializationTaints []string `json:"nodeInitializationTaints"`

	// node taints
	NodeTaints []string `json:"nodeTaints"`

	// orchestrator version
	// Required: true
	OrchestratorVersion *string `json:"orchestratorVersion"`

	// os sku
	// Required: true
	OsSku *int32 `json:"osSku"`

	// os type
	// Required: true
	OsType *int32 `json:"osType"`

	// security profile
	SecurityProfile *AgentPoolSecurityProfile `json:"securityProfile,omitempty"`

	// storage profile
	// Required: true
	StorageProfile *string `json:"storageProfile"`

	// vm size
	// Required: true
	VMSize *string `json:"vmSize"`

	// vnet cidrs
	// Required: true
	VnetCidrs []string `json:"vnetCidrs"`

	// vnet subnet ID
	// Required: true
	VnetSubnetID *string `json:"vnetSubnetID"`

	// workload runtime
	WorkloadRuntime *int32 `json:"workloadRuntime,omitempty"`
}

// Validate validates this provision profile
func (m *ProvisionProfile) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) validateAgentPoolWindowsProfile(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) validateArchitecture(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) validateArtifactStreamingProfile(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) validateCustomKubeletConfig(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) validateCustomLinuxOSConfig(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) validateDistro(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) validateGpuProfile(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) validateLocalDNSProfile(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) validateMaxPods(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) validateMode(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) validateName(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) validateOrchestratorVersion(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) validateOsSku(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) validateOsType(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) validateSecurityProfile(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) validateStorageProfile(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) validateVMSize(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) validateVnetCidrs(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) validateVnetSubnetID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validate this provision profile based on the context it is used
func (m *ProvisionProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProvisionProfile) contextValidateAgentPoolWindowsProfile(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) contextValidateArtifactStreamingProfile(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) contextValidateCustomKubeletConfig(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) contextValidateCustomLinuxOSConfig(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) contextValidateGpuProfile(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) contextValidateLocalDNSProfile(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *ProvisionProfile) contextValidateSecurityProfile(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

// MarshalBinary interface implementation
func (m *ProvisionProfile) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *ProvisionProfile) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
