/*
Portions Copyright (c) Microsoft Corporation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Azure/karpenter-provider-azure/pkg/provisionclients/models"
)

// NewNodeBootstrappingGetParams creates a new NodeBootstrappingGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNodeBootstrappingGetParams() *NodeBootstrappingGetParams {
	_ = "STUB: not implemented"
	return nil
}

// NewNodeBootstrappingGetParamsWithTimeout creates a new NodeBootstrappingGetParams object
// with the ability to set a timeout on a request.
func NewNodeBootstrappingGetParamsWithTimeout(timeout time.Duration) *NodeBootstrappingGetParams {
	_ = "STUB: not implemented"
	return nil
}

// NewNodeBootstrappingGetParamsWithContext creates a new NodeBootstrappingGetParams object
// with the ability to set a context for a request.
func NewNodeBootstrappingGetParamsWithContext(ctx context.Context) *NodeBootstrappingGetParams {
	_ = "STUB: not implemented"
	return nil
}

// NewNodeBootstrappingGetParamsWithHTTPClient creates a new NodeBootstrappingGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewNodeBootstrappingGetParamsWithHTTPClient(client *http.Client) *NodeBootstrappingGetParams {
	_ = "STUB: not implemented"
	return nil
}

/*
NodeBootstrappingGetParams contains all the parameters to send to the API endpoint

	for the node bootstrapping get operation.

	Typically these are written to a http.Request.
*/
type NodeBootstrappingGetParams struct {

	/* Parameters.

	   Values required to determine NodeBootstrapping values.
	*/
	Parameters *models.ProvisionValues

	// ResourceGroupName.
	ResourceGroupName string

	// ResourceName.
	ResourceName string

	// SubscriptionID.
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the node bootstrapping get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NodeBootstrappingGetParams) WithDefaults() *NodeBootstrappingGetParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the node bootstrapping get params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *NodeBootstrappingGetParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the node bootstrapping get params
func (o *NodeBootstrappingGetParams) WithTimeout(timeout time.Duration) *NodeBootstrappingGetParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the node bootstrapping get params
func (o *NodeBootstrappingGetParams) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the node bootstrapping get params
}

func (o *NodeBootstrappingGetParams) WithContext(ctx context.Context) *NodeBootstrappingGetParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the node bootstrapping get params
func (o *NodeBootstrappingGetParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the node bootstrapping get params
	return
}

func (o *NodeBootstrappingGetParams) WithHTTPClient(client *http.Client) *NodeBootstrappingGetParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the node bootstrapping get params
func (o *NodeBootstrappingGetParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithParameters adds the parameters to the node bootstrapping get params
}

func (o *NodeBootstrappingGetParams) WithParameters(parameters *models.ProvisionValues) *NodeBootstrappingGetParams {
	_ = "STUB: not implemented"
	return nil
}

// SetParameters adds the parameters to the node bootstrapping get params
func (o *NodeBootstrappingGetParams) SetParameters(parameters *models.ProvisionValues) {
	_ = "STUB: not implemented"
	return
}

// WithResourceGroupName adds the resourceGroupName to the node bootstrapping get params
func (o *NodeBootstrappingGetParams) WithResourceGroupName(resourceGroupName string) *NodeBootstrappingGetParams {
	_ = "STUB: not implemented"
	return nil
}

// SetResourceGroupName adds the resourceGroupName to the node bootstrapping get params
func (o *NodeBootstrappingGetParams) SetResourceGroupName(resourceGroupName string) {
	_ = "STUB: not implemented"
	return
}

// WithResourceName adds the resourceName to the node bootstrapping get params
func (o *NodeBootstrappingGetParams) WithResourceName(resourceName string) *NodeBootstrappingGetParams {
	_ = "STUB: not implemented"
	return nil
}

// SetResourceName adds the resourceName to the node bootstrapping get params
func (o *NodeBootstrappingGetParams) SetResourceName(resourceName string) {
	_ = "STUB: not implemented"
	return
}

// WithSubscriptionID adds the subscriptionID to the node bootstrapping get params
func (o *NodeBootstrappingGetParams) WithSubscriptionID(subscriptionID string) *NodeBootstrappingGetParams {
	_ = "STUB: not implemented"
	return nil
}

// SetSubscriptionID adds the subscriptionId to the node bootstrapping get params
func (o *NodeBootstrappingGetParams) SetSubscriptionID(subscriptionID string) {
	_ = "STUB: not implemented"
	return
}

// WriteToRequest writes these params to a swagger request
func (o *NodeBootstrappingGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// path param resourceGroupName

// path param resourceName

// path param subscriptionId
