/*
Portions Copyright (c) Microsoft Corporation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Azure/karpenter-provider-azure/pkg/provisionclients/models"
)

// NodeBootstrappingGetReader is a Reader for the NodeBootstrappingGet structure.
type NodeBootstrappingGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NodeBootstrappingGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// NewNodeBootstrappingGetOK creates a NodeBootstrappingGetOK with default headers values
func NewNodeBootstrappingGetOK() *NodeBootstrappingGetOK { _ = "STUB: not implemented"; return nil }

/*
NodeBootstrappingGetOK describes a response with status code 200, with default header values.

OK
*/
type NodeBootstrappingGetOK struct {
	Payload *models.NodeBootstrapping
}

// IsSuccess returns true when this node bootstrapping get o k response has a 2xx status code
func (o *NodeBootstrappingGetOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this node bootstrapping get o k response has a 3xx status code
	return false
}

func (o *NodeBootstrappingGetOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this node bootstrapping get o k response has a 4xx status code
	return false
}

func (o *NodeBootstrappingGetOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this node bootstrapping get o k response has a 5xx status code
	return false
}

func (o *NodeBootstrappingGetOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this node bootstrapping get o k response a status code equal to that given
	return false
}

func (o *NodeBootstrappingGetOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the node bootstrapping get o k response
	return false
}

func (o *NodeBootstrappingGetOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *NodeBootstrappingGetOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *NodeBootstrappingGetOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *NodeBootstrappingGetOK) GetPayload() *models.NodeBootstrapping {
	_ = "STUB: not implemented"
	return nil
}

func (o *NodeBootstrappingGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewNodeBootstrappingGetDefault creates a NodeBootstrappingGetDefault with default headers values
func NewNodeBootstrappingGetDefault(code int) *NodeBootstrappingGetDefault {
	_ = "STUB: not implemented"
	return nil
}

/*
NodeBootstrappingGetDefault describes a response with status code -1, with default header values.

Error response describing why the operation failed.
*/
type NodeBootstrappingGetDefault struct {
	_statusCode int

	Payload string
}

// IsSuccess returns true when this node bootstrapping get default response has a 2xx status code
func (o *NodeBootstrappingGetDefault) IsSuccess() bool { _ = "STUB: not implemented"; return false }

// IsRedirect returns true when this node bootstrapping get default response has a 3xx status code
func (o *NodeBootstrappingGetDefault) IsRedirect() bool { _ = "STUB: not implemented"; return false }

// IsClientError returns true when this node bootstrapping get default response has a 4xx status code
func (o *NodeBootstrappingGetDefault) IsClientError() bool { _ = "STUB: not implemented"; return false }

// IsServerError returns true when this node bootstrapping get default response has a 5xx status code
func (o *NodeBootstrappingGetDefault) IsServerError() bool { _ = "STUB: not implemented"; return false }

// IsCode returns true when this node bootstrapping get default response a status code equal to that given
func (o *NodeBootstrappingGetDefault) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the node bootstrapping get default response
}

func (o *NodeBootstrappingGetDefault) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *NodeBootstrappingGetDefault) Error() string { _ = "STUB: not implemented"; return "" }

func (o *NodeBootstrappingGetDefault) String() string { _ = "STUB: not implemented"; return "" }

func (o *NodeBootstrappingGetDefault) GetPayload() string { _ = "STUB: not implemented"; return "" }
